# Import Libraries

In [1]:
from GenerateSyntheticData import *
from MeanDecreaseImpurity import *

import sklearn.ensemble as Ensemble
import sklearn.tree as Tree
import pandas as pd
import numpy as np

# Generate Synthetic Test Data

In [2]:
X, y = get_test_dataset(
    n_features=40,
    n_informative=5, 
    n_redundant=30,
    n_samples=10000,
    sigma_std=0.1
)

# Fit MDI

In [3]:
import warnings
warnings.filterwarnings('ignore')

classifier = Tree.DecisionTreeClassifier(
    criterion="entropy",
    max_features=1,
    class_weight="balanced",
    min_weight_fraction_leaf=0,
)

classifier = Ensemble.BaggingClassifier(
    base_estimator=classifier,
    n_estimators=1000,
    max_features=1.0,
    max_samples=1.0,
    oob_score=False,
)

fit = classifier.fit(X, y)

result = feature_importance_MDI(
    fit, 
    X.columns,
);

In [4]:
result

          Mean  StandardDeviation
I_0   0.021176           0.000417
I_1   0.045948           0.001649
I_2   0.034735           0.000639
I_3   0.014692           0.000139
I_4   0.030787           0.000780
N_0   0.011540           0.000085
N_1   0.011659           0.000086
N_2   0.011475           0.000086
N_3   0.011530           0.000085
N_4   0.011621           0.000088
R_0   0.032261           0.000843
R_1   0.020240           0.000392
R_2   0.014634           0.000142
R_3   0.014531           0.000139
R_4   0.014627           0.000145
R_5   0.044416           0.001554
R_6   0.014718           0.000149
R_7   0.036157           0.000709
R_8   0.031431           0.000797
R_9   0.020455           0.000395
R_10  0.020311           0.000397
R_11  0.031964           0.000806
R_12  0.034632           0.000697
R_13  0.044757           0.001582
R_14  0.019737           0.000376
R_15  0.042612           0.001486
R_16  0.045576           0.001572
R_17  0.020771           0.000395
R_18  0.045014           0.001649
R_19  0.032176           0.000817
R_20  0.014709           0.000146
R_21  0.020788           0.000411
R_22  0.014662           0.000147
R_23  0.021309           0.000418
R_24  0.035691           0.000688
R_25  0.014577           0.000143
R_26  0.019598           0.000377
R_27  0.042967           0.001498
R_28  0.014942           0.000146
R_29  0.014575           0.000148

In [5]:
result = result.sort_values("Mean", ascending=False)
result

          Mean  StandardDeviation
I_1   0.045948           0.001649
R_16  0.045576           0.001572
R_18  0.045014           0.001649
R_13  0.044757           0.001582
R_5   0.044416           0.001554
R_27  0.042967           0.001498
R_15  0.042612           0.001486
R_7   0.036157           0.000709
R_24  0.035691           0.000688
I_2   0.034735           0.000639
R_12  0.034632           0.000697
R_0   0.032261           0.000843
R_19  0.032176           0.000817
R_11  0.031964           0.000806
R_8   0.031431           0.000797
I_4   0.030787           0.000780
R_23  0.021309           0.000418
I_0   0.021176           0.000417
R_21  0.020788           0.000411
R_17  0.020771           0.000395
R_9   0.020455           0.000395
R_10  0.020311           0.000397
R_1   0.020240           0.000392
R_14  0.019737           0.000376
R_26  0.019598           0.000377
R_28  0.014942           0.000146
R_6   0.014718           0.000149
R_20  0.014709           0.000146
I_3   0.014692           0.000139
R_22  0.014662           0.000147
R_2   0.014634           0.000142
R_4   0.014627           0.000145
R_25  0.014577           0.000143
R_29  0.014575           0.000148
R_3   0.014531           0.000139
N_1   0.011659           0.000086
N_4   0.011621           0.000088
N_0   0.011540           0.000085
N_3   0.011530           0.000085
N_2   0.011475           0.000086

# Plot Results

In [6]:
import plotly.express as px
import plotly

result["FeatureName"] = result.index
fig = px.bar(
    result,
    x="Mean", 
    y="FeatureName",
    error_x="StandardDeviation"    
)

fig.update_layout(
    title="MDA Results",
    xaxis_title="Feature Name",
    yaxis_title="Feature Importance",
    template="plotly_dark",
    width=800, height=1200,
    # legend_title="Legend Title",
    # font=dict(
    #     family="Courier New, monospace",
    #     size=18,
    #     color="RebeccaPurple"
    # )
)

# fig.show()

In [29]:
x = json.loads(plotly.io.to_json(fig, pretty=False, remove_uids=True))

type(x["data"])

list

# Save Results

In [7]:
fig.write_image("./Figs/MDI_results.png",format='png',engine='kaleido')

ValueError:
Image export using the "kaleido" engine requires the kaleido package,
which can be installed using pip:
    $ pip install -U kaleido